### ISSUE TITLE
Simulation environment classes

### ISSUE THREAD

**Issue by OleguerCanal** [CampusAI/Hamiltonian-Generative-Networks#1]
I was thinking in trying to have an interface very similar to the ones of GYM environments (without actions) so later its easier to do some tests with them.

I think we should have an "environments" folder and have all the environments in there

My idea was to have something like:

```python
from environments.pendulum import Pendulum
env = Pendulum(mass=1, length=1)  # Instantiate class with its parameters
env.set(p=30, q=10)  # Fix some initial conditions. In this case p is 1-dim angle and q 1-dim ang vel
image, p, q = env.step(delta_time=0.1)  # Do a step of 0.1 seconds on the environment and get its info (environment is now in this new state)
```
What do you think @fedetask @charlio23?

**Comment by charlio23** [comment]
I think it is cool! I will start implementing a pendulum class. I will open a separate issue for that

**Comment by OleguerCanal** [comment]
I just thought that to create datasets it would also be useful to have a method which repeatedly calls step and returns a list of images, a list of positions and a list of moments.

This should be for a given amount of time and with a fixed time step.

something like:
```python
images, ps, qs = env.evolution(total_time=10, deltatime=0.1)
```

Maybe this method could be implemented in a abstract class as its going to be shared between all simulation environments

**Comment by fedetask** [comment]
I think `evolution()` could also be a method of the environment. Such as having an abstract class
```python
class Env(ABC):
    @abstractmethod
    def step(p, q):  # p and q are numpy ndarrays
        pass
    @abstractmethod
    def evolution(time, delta_time):  # The one you're saying
        pass 
```

And then all our environments will extend `Env`

**Comment by OleguerCanal** [comment]
Yes, thats what I meant. Check out this pull request to see how it is implemented:
https://github.com/CampusAI/Hamiltonian-Generative-Networks/pull/6

**Comment by OleguerCanal** [comment]
@charlio23 they say they smooth the circles "so they dont have hard edges".

Could we do the same?

**Comment by OleguerCanal** [comment]
@charlio23 they use [scipy ode integrator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html) to solve the ODEs for the simulators. I think we should do the same instead of hardcoding the solutions. What do you guys think? @fedetask

**Comment by OleguerCanal** [comment]
@charlio23 check out the results section of the paper, they explain how they create the datasets, we should do the same.

**Comment by OleguerCanal** [comment]
@charlio23 could you add a method to the environment class which creates a rollout from random initial conditions and takes a seed?
As we discussed the other day, it would be nice to create the data samples "on the fly" while training.

I was thinking of somehting like:

```python
env = Pendulum(mass=1, length=1)
hgn = HGN(...)
for i in range(training_steps):
    rollouts = env.sample_random_rollout(seed=i, number_of_frames=100, delta_time=0.1, number_of_rollouts=16)
    hgn.fit(rollouts, ...)
```

**Comment by charlio23** [comment]
Linked to environment and pendulum PR
