### ISSUE TITLE
Integrator

### ISSUE THREAD

**Issue by OleguerCanal** [CampusAI/Hamiltonian-Generative-Networks#10]
We need to implement the **leapfrog integrator** from the HNN.
We should also implement **euler integration** and **runge-kutta rk4** integrator.

I'm thinking of having an integrator class and pass it to the model. Something like:

```python
integrator = Integrator(method="euler")
q_next, p_next = integrator.step(q_now, p_now, HNN, dt)
```

What do you guys think @charlio23  @fedetask

**Comment by OleguerCanal** [comment]
Not sure if it will be easier to use [scipy](https://docs.scipy.org/doc/scipy/reference/integrate.html) or just use write ours which ises network HNN

**Comment by OleguerCanal** [comment]
[This](https://www.uio.no/studier/emner/matnat/astro/AST2000/h18/undervisningsmateriell_h2018/Numerical%20Compendium/integration_of_differential_equations.pdf) might be useful

**Comment by charlio23** [comment]
I will take a look at RK4 and leapfrog implentations and see if we can import them to our simulations

**Comment by OleguerCanal** [comment]
I think in the simulations you should use some already implemented integrator (you provide equation and initial conditions and get evolution). I think you implemented Euler integration right? I dont think Euler is very good...
What do you think @charlio23
