### ISSUE TITLE
Pytorch DataLoader class. Data API for feeding the networks

### ISSUE THREAD

**Issue by charlio23** [CampusAI/Hamiltonian-Generative-Networks#16]
A pytorch dataloader is required to sample data and forward it to the networks.
`class EnvironmentSampler(Dataset):`
The class will have the following structure:

- A constructor: `def __init__(self, environment, length):`
where `environment` is an `Environment` instance to indicate the physical system to draw data from; and `length` indicates the length of the dataset (since we can keep sampling random rollouts we avoid having an infinite size).

- `    def __len__(self):
        return self.length`
- An iterable call `def __getitem__(self, i):`
this will be called each time a batch is required. A rollout is sampled and converted as a pytorch tensor to be forwarded to the network. It should perform standarization of the data (maybe just mean substraction?)

 Sample code will be provided in the same file to show its usage.

**Comment by OleguerCanal** [comment]
Sounds very good! Maybe we also need to pass batch_size, delta_time, image_resolution, randomization stuff... right? @charlio23

**Comment by charlio23** [comment]
yes yes, all in the constructor method! I forgot it in the comment.
