### ISSUE TITLE
Decoder architecture

### ISSUE THREAD

**Issue by OleguerCanal** [CampusAI/Hamiltonian-Generative-Networks#19]
In the decoder, how do we go from 4x4x16 -> 32x32X3.
Each residual block:
- Upsamples x2 the resolution e.g. in first block: 4x4x16 -> 8x8x16
-  Applies 2 convs of 64 filters: e.g. in first block: 8x8x16 -> 8x8x64

How do we add the residual tensor (yhe one that skips the convs in the residual blocks)?

Inspired by: https://arxiv.org/abs/1710.10196

**Comment by stathius** [comment]
In the original ResNet paper they mention two ways to fix the change in number of channels (https://arxiv.org/abs/1512.03385).

"(A) The shortcut still performs identity mapping, with extra zero entries padded for increasing dimensions. This option introduces no extra parameter; (B) The projection shortcut in Eqn.(2) is used to match dimensions (done by 1×1 convolutions). For both options, when the shortcuts go across feature maps of two sizes, they are performed with a stride of 2."

Earlier they say:

"The dimensions of x and F must be equal in Eqn.(1). If this is not the case (e.g., when changing the input/output channels), we can perform a linear projection Ws by the shortcut connections to match the dimensions:
y = F (x, {Wi }) + Ws x. (2)
We can also use a square matrix Ws in Eqn.(1). But we will show by experiments that the identity mapping is sufficient for addressing the degradation problem and is economical, and thus Ws is only used when matching dimensions."

**Comment by stathius** [comment]
So overall, we can either pad with zeros or learn a linear projection matrix that will be of dimension `num_input_channels x num_ouput_channels` (can be considered equal to 1x1 convolution).

**Comment by OleguerCanal** [comment]
Sounds good! Thanks for the research!
What do you think would be best? Both options seem easy to implement.
Should we define a parameter on which alternative to use and experiment? (or maybe it is not that urgent to experiment on that)

**Comment by fedetask** [comment]
Nice! From their paper, there doesn't seem to be a big difference between the two, and in much smaller model there may not be any difference at all. Making the assumption that the difference is negligible, I would go for the zero-padding just because it's faster. But we can give one try to both. What do you think?
