### ISSUE TITLE
Architectures

### ISSUE THREAD

**Issue by OleguerCanal** [CampusAI/Hamiltonian-Generative-Networks#2]
I was thinking it would be good to have the three different architectures the model combines in different scripts so things are a bit more organized.

Maybe it would be good to have an "architectures" folder and inside there a script for each module. Then a script which combines all of them as a single model.

What do you think @fedetask ?

**Comment by fedetask** [comment]
You mean a python file for each architecture? I think it's okay, maybe if the code is short we can have just one file, but I think it won't be that short

**Comment by OleguerCanal** [comment]
Yes, maybe lets do one for each for now and we'll see. I dont think there will be much more stuff in this folder so its ok. Is the folder name "networks" better than "architectures" maybe?

Would also be cool to have some methods to load/save architectures and learned weights.

**Comment by fedetask** [comment]
Sure, I'll make a `common.py` or `utils.py` script that contains functions such as loading/saving weights and other things that we'll find useful

**Comment by OleguerCanal** [comment]
If you make all the modules inherit from some abstract class maybe you can put it there and have a sinlge implementation for all of them. Not sure if its cleaner than a helper file

**Comment by fedetask** [comment]
Actually there must be already the pytorch methods for this. I'll check
