### ISSUE TITLE
Implement GECO to stabilize learning

### ISSUE THREAD

**Issue by OleguerCanal** [CampusAI/Hamiltonian-Generative-Networks#21]
Danilo J Rezende and Fabio Viola. Generalized elbo with constrained optimization, geco. Workshop on Bayesian Deep Learning, NeurIPS, 2018.

**Comment by OleguerCanal** [comment]
How is this going @stathius ? We successfully trained the deterministic version but we would like to see how the variational works.

**Comment by stathius** [comment]
Will start implementation this evening. I do not expect this to be a blocker for training the variational model. It should train fine with the vanilla loss implementation (given it's ok). Actually we should train without geco first to debug the variational part.

**Comment by OleguerCanal** [comment]
Ok, we will train with a fixed lagrange multiplier for now then. You can branch from master and implement it into a "geco" branch. We will use it around line 120 of generative_hamiltonian_network.py

**Comment by fedetask** [comment]
There is an open pull request that should provide a stable and standardized code to develop from. By this evening it should be merged to master and you can start developing on top of that.

Sorry if the master branch was not clean and stable in the last days.

**Comment by fedetask** [comment]
PR #30 is merged to `master` and now `master` should be stable for training and feature development.

**Comment by stathius** [comment]
Thanks that's great news. I think I will implement it on a known and stable VAE for MNIST and then transfer to HGN. It will be easier to debug I believe.
