### ISSUE TITLE
Bugs/Improvements in networks

### ISSUE THREAD

**Issue by OleguerCanal** [CampusAI/Hamiltonian-Generative-Networks#25]
- [x] No activation on the mean and logvar Conv2D of the encoder.
- [x] Encoder returns logvar, not stddev
- [ ] Think about adding Pooling Layer
- [ ] Hamiltonian think about 3d conv layer

**Comment by fedetask** [comment]
Should I create a new branch for these fixes?

**Comment by OleguerCanal** [comment]
Yes, I think thats better
