### ISSUE TITLE
Issues in the current parameters and training

### ISSUE THREAD

**Issue by fedetask** [CampusAI/Hamiltonian-Generative-Networks#41]
These are important issues that we need to address in order to have a stable and working `master` branch.

- [x] The `world_size` parameter must be a parameter of the environment and not of the dataset, since different environments require different world sizes. 
- [x] The training is broken in `master`, as `dataset_len` is computed as `dataset_len = params["optimization"]["epochs"] * params["optimization"]["batch_size"]`. It is being addressed in PR #40.
- ~~Wrong behavior of `Dataloader` as it expects the `__get_item__()` method of `EnvironmentSampler` to return single samples instead of batches. See the [related comment](https://github.com/CampusAI/Hamiltonian-Generative-Networks/pull/37#discussion_r508878695).~~

**Comment by charlio23** [comment]
can we close this?
