### ISSUE TITLE
Fix Hamiltonian network

### ISSUE THREAD

**Issue by OleguerCanal** [CampusAI/Hamiltonian-Generative-Networks#68]
Layer1: channels=num_hidden//2, kernel_shape=3, stride=1, padding=SAME
Layer2: channels=num_hidden, kernel_shape=2, stride=2, padding=VALID
Layer3: channels=num_hidden, kernel_shape=2, stride=1, padding=SAME
Layer4: channels=num_hidden, kernel_shape=2, stride=1, padding=SAME
Layer5: channels=1, kernel_shape=2, stride=2, padding=VALID
I think we were using a softplus nonlinearity (remember we need this to be smooth because of differentiation).

The last convolution has 1 output channel and then the Hamiltonian is the sum over the spatial locations (e.g. we were simulating independently each channel).

**Comment by OleguerCanal** [comment]
"Potentially, if you did not use smooth non-linearities, but something like ReLu's, since the gradients of the loss w.r.t. Hamiltonian weights depend on second order derivatives, they will be 0. Hence if you use ReLu's your Hamiltonian network would never train (I think with the only caveat of the first layer). "

**Comment by fedetask** [comment]
Fixed in #76
